/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
soma_1_svc(op *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->a + argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}

float *
subtracao_1_svc(op *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = argp->a - argp->b;

	return &result;
}

float *
multiplicacao_1_svc(op *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = argp->a * argp->b;

	return &result;
}

float *
divisao_1_svc(op *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->a / argp->b;

	return &result;
}
