/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct op {
	float a;
	float b;
};
typedef struct op op;

#define CALC 0x1fce1fce
#define CALC 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  float * soma_1(op *, CLIENT *);
extern  float * soma_1_svc(op *, struct svc_req *);
#define subtracao 2
extern  float * subtracao_1(op *, CLIENT *);
extern  float * subtracao_1_svc(op *, struct svc_req *);
#define multiplicacao 3
extern  float * multiplicacao_1(op *, CLIENT *);
extern  float * multiplicacao_1_svc(op *, struct svc_req *);
#define divisao 4
extern  float * divisao_1(op *, CLIENT *);
extern  float * divisao_1_svc(op *, struct svc_req *);
extern int calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  float * soma_1();
extern  float * soma_1_svc();
#define subtracao 2
extern  float * subtracao_1();
extern  float * subtracao_1_svc();
#define multiplicacao 3
extern  float * multiplicacao_1();
extern  float * multiplicacao_1_svc();
#define divisao 4
extern  float * divisao_1();
extern  float * divisao_1_svc();
extern int calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_op (XDR *, op*);

#else /* K&R C */
extern bool_t xdr_op ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
