/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float
calc(char *host, float a, float b, char ope)
{
	CLIENT *clnt;
	float  *result;
	op ops;

	ops.a = a;
	ops.b = b;

	clnt = clnt_create (host, CALC, CALC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	if( ope == '+'){
		result = soma_1(&ops, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	if( ope == '-'){
		result = subtracao_1(&ops, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	if( ope == '*'){
		result = multiplicacao_1(&ops, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	if( ope == '/'){
		result = divisao_1(&ops, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

	clnt_destroy (clnt);

	return *result;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	float a,b;
	char op;
   printf("digite a:\n");
   scanf("%f",&a);
   printf("digite b:\n");
   scanf("%f",&b);
   printf("digite op:\n");
	scanf("%s",&op);

	host = argv[1];
	printf("resposta: %f\n", calc(host, a, b, op));
	exit (0);
}
